# Generated by Django 4.0.5 on 2022-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_ac_holder_nm_tally_ledger_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_vouchers',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ledger_vouchers',
            name='debit',
            field=models.IntegerField(),
        ),
    ]
