# Generated by Django 4.0.5 on 2022-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_ledger_vouchers_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlist',
            name='vouch_num',
            field=models.IntegerField(default=True),
        ),
    ]
