# Generated by Django 4.0.5 on 2022-09-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_voucherlist_vouch_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_closingbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.FloatField()),
                ('stock_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroup')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item')),
            ],
        ),
    ]
