# Generated by Django 4.0.5 on 2022-09-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_stock_closingbalance_stock_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_closingbalance',
            name='stock_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock_closingbalance',
            name='stock_item',
            field=models.IntegerField(null=True),
        ),
    ]
