# Generated by Django 4.0.5 on 2022-09-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_stockgroup_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgroup',
            name='closing_balance',
            field=models.FloatField(null=True),
        ),
    ]
