# Generated by Django 4.0.5 on 2022-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_stockgroup_closing_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='closing_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
