# Generated by Django 4.0.5 on 2022-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_tally_ledger_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_ledger',
            name='closing_balance',
            field=models.FloatField(default=0),
        ),
    ]
