# Generated by Django 4.0.5 on 2022-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_tally_ledger_closing_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trialbalance_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.IntegerField()),
                ('deposits', models.IntegerField()),
                ('loan', models.IntegerField()),
                ('sundry', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('bank', models.IntegerField()),
            ],
        ),
    ]
