# Generated by Django 4.0.5 on 2022-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_trialbalance_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance_assets',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='trialbalance_assets',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='trialbalance_assets',
            name='deposits',
        ),
        migrations.RemoveField(
            model_name='trialbalance_assets',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='trialbalance_assets',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='trialbalance_assets',
            name='sundry',
        ),
        migrations.AddField(
            model_name='trialbalance_assets',
            name='closing_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialbalance_assets',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
