# Generated by Django 4.0.5 on 2022-10-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_remove_trialbalance_assets_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance_assets',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialbalance_assets',
            name='debit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialbalance_assets',
            name='total_credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialbalance_assets',
            name='total_debit',
            field=models.IntegerField(null=True),
        ),
    ]
