# Generated by Django 4.0.5 on 2022-10-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_trialbalance_assets_credit_trialbalance_assets_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance_assets',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger'),
        ),
    ]
