# Generated by Django 4.0.5 on 2022-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_trialbalance_assets_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance_assets',
            name='type',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
